name = "Rosenbluth"
uuid = "ccaa1f9c-055d-4c5e-8e40-d5dcb2253666"
authors = ["Tom Roberts"]
version = "1.0.0-DEV"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34.4"
TestItemRunner = "1.0.5"
TestItems = "1.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Test", "TestItems", "TestItemRunner"]
